config/routes.rb
Rails.application.routes.draw do

root "invoices#index"

resources :invoices

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
    belongs_to :user
    has_many :items, dependent: :destroy
    validates :invoice_number, :client, presence: true
    accepts_nested_attributes_for :items

    def self.calculate_total(items)
        total = 0
        items.each do |index, item| 
            total += item[:price].to_f
        end
        return total
    end
end
 

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :invoice
    validates :description, :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :invoices, dependent: :destroy
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
      # before action to sert clients but restricted to specific actions (define the method in this file)

      # add destory action

      # add invoice status

  
  def index
    @invoices = Invoice.all
  end

  def show
    @invoice = Invoice.find(params[:id])
  end

  def new
    @invoice = Invoice.new
    @invoice.items.build
  end

  def create

    params = invoice_params
    params["total"] = Invoice.calculate_total(params[:items_attributes])
    @invoice = Invoice.new(params)

    # where to get user_id from? doesnt make sense to pass from form 
    if @invoice.save
      redirect_to @invoice
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def invoice_params
      params
        .require(:invoice)
        .permit(:invoice_number, :user_id, :client,
          items_attributes: [:id, :description, :price])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/index.html.erb
<h1>Invoices</h1>

<table>
  <thead>
    <tr>
      <th>Invoice Number</th>
      <th>Client</th>
      <th>Total</th>

    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= link_to invoice.invoice_number, invoice %></td>
        <td><%= invoice.client %></td>
        <td><%= invoice.total %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="new-invoice-button" >
  <%= link_to "New Invoice", new_invoice_path %>
</div>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= form_for @invoice do |form| %>

  <div>
    <%= form.label :invoice_number %><br>
    <%= form.text_field :invoice_number %>
    <% @invoice.errors.full_messages_for(:invoice_number).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div>
    <%= form.label :client %><br>
    <%= form.text_area :client %>
  </div>

  <div>
    <%= form.label :user_id %><br>
    <%= form.text_area :user_id %>
    <% @invoice.errors.full_messages_for(:user_id).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  
  
  <%= form.fields_for :items do |item_subform|  %>
    <h4>Items</h4>
    <div>
      <%= item_subform.label :description %><br>
      <%= item_subform.text_field :description %><br>

      <%= item_subform.label :price %><br>
      <%= item_subform.text_field :price %>
    </div>
  <% end %>
  

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices/show.html.erb
<h1><%= @invoice.invoice_number %></h1>

<table>
  <thead>
    </tr>
    <p><strong>Client: </strong><%= @invoice.client %></p>
    <tr>
    </tr><p><strong>Items:</strong><tr>
    <tr>
      <th>Description</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <% @invoice.items.each do |item| %>
      <tr>
        <td><%= item.description %></td>
        <td><%= item.price %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div>
  <p><strong>Invoice total: </strong>$<%= @invoice.total %></p>
</div>

<div class="new-invoice-button" >
  <%= link_to "Invoices", invoices_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InvoicingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>